DROP TABLE IF EXISTS `tb_cost_budget`;
CREATE TABLE `tb_cost_budget` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '预算ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `budget_type` int(4) DEFAULT NULL COMMENT '预算类型(1:月度, 2:季度, 3:年度)',
  `budget_period` varchar(20) DEFAULT NULL COMMENT '预算期间(如2023-01, 2023-Q1, 2023)',
  `budget_amount` decimal(10,2) DEFAULT 0.00 COMMENT '预算金额',
  `used_amount` decimal(10,2) DEFAULT 0.00 COMMENT '已使用金额',
  `start_date` datetime DEFAULT NULL COMMENT '起始日期',
  `end_date` datetime DEFAULT NULL COMMENT '结束日期',
  `status` int(4) DEFAULT 1 COMMENT '状态(0:未启用, 1:进行中, 2:已结束, 3:已超出)',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  INDEX `idx_user_dept` (`user_id`, `dept_id`),
  INDEX `idx_period` (`budget_type`, `budget_period`),
  INDEX `idx_date_range` (`start_date`, `end_date`),
  INDEX `idx_status` (`status`),
  CONSTRAINT `fk_cost_budget_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cost_budget_dept` FOREIGN KEY (`dept_id`) REFERENCES `sys_dept` (`dept_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='邮费预算表'; 