CREATE TABLE `tb_cost` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '邮费主键ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `logistics_company` varchar(100) NOT NULL COMMENT '物流公司名称',
  `last_four_digits` varchar(4) DEFAULT NULL,
  `full_tracking_number` varchar(50) DEFAULT NULL COMMENT '完整运单号',
  `cost_amount` decimal(10,2) NOT NULL COMMENT '花费金额',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `date_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `shipping_date` datetime DEFAULT NULL COMMENT '发货日期',
  `recipient_province` varchar(50) DEFAULT NULL COMMENT '收件省份',
  `recipient_city` varchar(50) DEFAULT NULL COMMENT '收件城市',
  `recipient_district` varchar(50) DEFAULT NULL COMMENT '收件区县',
  `recipient_address` text COMMENT '收件详细地址',
  `weight` decimal(10,2) DEFAULT NULL COMMENT '包裹重量(kg)',
  `receipt_image_url` varchar(255) DEFAULT NULL COMMENT '运单图片存储路径',
  `image_upload_time` datetime DEFAULT NULL COMMENT '图片上传时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_full_tracking_number` (`full_tracking_number`),
  KEY `idx_shipping_date` (`shipping_date`),
  KEY `idx_recipient_province` (`recipient_province`),
  KEY `idx_recipient_city` (`recipient_city`),
  KEY `idx_recipient_district` (`recipient_district`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COMMENT='邮费表' 